// <auto-generated />
using System;
using AiRecruitmentPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AiRecruitmentPlatform.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260726114345_AddJobPostingAndScreeningCriteria")]
    partial class AddJobPostingAndScreeningCriteria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CandidateEducation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CandidateProfileInformationId")
                        .HasColumnType("bigint")
                        .HasColumnName("candidate_profile_information_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("degree");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("field_of_study");

                    b.Property<string>("Grade")
                        .HasColumnType("longtext")
                        .HasColumnName("grade");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("institution");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_current");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_candidate_educations");

                    b.HasIndex("CandidateProfileInformationId")
                        .HasDatabaseName("ix_candidate_educations_candidate_profile_information_id");

                    b.ToTable("candidate_educations", (string)null);
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CandidateExperience", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CandidateProfileInformationId")
                        .HasColumnType("bigint")
                        .HasColumnName("candidate_profile_information_id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("company");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_current");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_candidate_experiences");

                    b.HasIndex("CandidateProfileInformationId")
                        .HasDatabaseName("ix_candidate_experiences_candidate_profile_information_id");

                    b.ToTable("candidate_experiences", (string)null);
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CandidateLanguage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CandidateProfileInformationId")
                        .HasColumnType("bigint")
                        .HasColumnName("candidate_profile_information_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Proficiency")
                        .HasColumnType("longtext")
                        .HasColumnName("proficiency");

                    b.HasKey("Id")
                        .HasName("pk_candidate_languages");

                    b.HasIndex("CandidateProfileInformationId")
                        .HasDatabaseName("ix_candidate_languages_candidate_profile_information_id");

                    b.ToTable("candidate_languages", (string)null);
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CandidateProfileInformation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("CurrentTitle")
                        .HasColumnType("longtext")
                        .HasColumnName("current_title");

                    b.Property<decimal?>("ExpectedSalaryMax")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("expected_salary_max");

                    b.Property<decimal?>("ExpectedSalaryMin")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("expected_salary_min");

                    b.Property<string>("ExperienceLevel")
                        .HasColumnType("longtext")
                        .HasColumnName("experience_level");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("ResumeUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("resume_url");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext")
                        .HasColumnName("summary");

                    b.Property<string>("TargetRole")
                        .HasColumnType("longtext")
                        .HasColumnName("target_role");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasColumnName("years_of_experience");

                    b.HasKey("Id")
                        .HasName("pk_candidate_profile_informations");

                    b.ToTable("candidate_profile_informations", (string)null);
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CandidateSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CandidateProfileInformationId")
                        .HasColumnType("bigint")
                        .HasColumnName("candidate_profile_information_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("Proficiency")
                        .HasColumnType("longtext")
                        .HasColumnName("proficiency");

                    b.HasKey("Id")
                        .HasName("pk_candidate_skills");

                    b.HasIndex("CandidateProfileInformationId")
                        .HasDatabaseName("ix_candidate_skills_candidate_profile_information_id");

                    b.ToTable("candidate_skills", (string)null);
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CandidateSocialLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CandidateProfileInformationId")
                        .HasColumnType("bigint")
                        .HasColumnName("candidate_profile_information_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("GitHubUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("git_hub_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("linked_in_url");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("PortfolioUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("portfolio_url");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_candidate_social_links");

                    b.HasIndex("CandidateProfileInformationId")
                        .IsUnique()
                        .HasDatabaseName("ix_candidate_social_links_candidate_profile_information_id");

                    b.ToTable("candidate_social_links", (string)null);
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CompanyProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyLogoUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("company_logo_url");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("company_name");

                    b.Property<string>("CompanySize")
                        .HasColumnType("longtext")
                        .HasColumnName("company_size");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("longtext")
                        .HasColumnName("contact_phone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<int?>("EstablishedYear")
                        .HasColumnType("int")
                        .HasColumnName("established_year");

                    b.Property<string>("Industry")
                        .HasColumnType("longtext")
                        .HasColumnName("industry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Location")
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("RegistrationNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("registration_number");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("Website")
                        .HasColumnType("longtext")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_company_profiles");

                    b.ToTable("company_profiles", (string)null);
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.JobPosting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("ApplicationsCount")
                        .HasColumnType("int")
                        .HasColumnName("applications_count");

                    b.Property<long>("CompanyProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_profile_id");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("currency");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employment_type");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("experience_level");

                    b.Property<string>("HiringManager")
                        .HasColumnType("longtext")
                        .HasColumnName("hiring_manager");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("location");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("RemoteType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("remote_type");

                    b.Property<string>("Requirements")
                        .HasColumnType("longtext")
                        .HasColumnName("requirements");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("longtext")
                        .HasColumnName("responsibilities");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("salary_max");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("salary_min");

                    b.Property<bool>("ShowSalary")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("show_salary");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<int>("ViewsCount")
                        .HasColumnType("int")
                        .HasColumnName("views_count");

                    b.HasKey("Id")
                        .HasName("pk_job_postings");

                    b.HasIndex("CompanyProfileId")
                        .HasDatabaseName("ix_job_postings_company_profile_id");

                    b.ToTable("job_postings", (string)null);
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.JobScreeningQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<string>("IdealAnswer")
                        .HasColumnType("longtext")
                        .HasColumnName("ideal_answer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsKnockout")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_knockout");

                    b.Property<long>("JobPostingId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_posting_id");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("longtext")
                        .HasColumnName("options_json");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("question_type");

                    b.HasKey("Id")
                        .HasName("pk_job_screening_questions");

                    b.HasIndex("JobPostingId")
                        .HasDatabaseName("ix_job_screening_questions_job_posting_id");

                    b.ToTable("job_screening_questions", (string)null);
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.JobSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<long>("DisplayOrder")
                        .HasColumnType("bigint")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsMandatory")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_mandatory");

                    b.Property<long>("JobPostingId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_posting_id");

                    b.Property<int>("MinimumYearsExperience")
                        .HasColumnType("int")
                        .HasColumnName("minimum_years_experience");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("skill_name");

                    b.HasKey("Id")
                        .HasName("pk_job_skills");

                    b.HasIndex("JobPostingId")
                        .HasDatabaseName("ix_job_skills_job_posting_id");

                    b.ToTable("job_skills", (string)null);
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.RecruiterNotificationPreference", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("ApplicationUpdates")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("application_updates");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_on");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_notifications");

                    b.Property<bool>("InterviewReminders")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("interview_reminders");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("modified_by");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("modified_on");

                    b.Property<bool>("PushNotifications")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("push_notifications");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_recruiter_notification_preferences");

                    b.ToTable("recruiter_notification_preferences", (string)null);
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Infrastructure.Identity.Models.ApplicationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("avatar_url");

                    b.Property<string>("CompanyId")
                        .HasColumnType("longtext")
                        .HasColumnName("company_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsOnboardingCompleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_onboarding_completed");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("refresh_token_expiry");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3584782f-084b-47f0-8c6b-544d7c8a16a0",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@airecruitmentplatform.com",
                            EmailConfirmed = true,
                            FirstName = "Super",
                            IsOnboardingCompleted = false,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@AIRECRUITMENTPLATFORM.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAENjlAJecB6CWZcpGvAURCjf1Nd5HFkpzxFJYoNVNJ/yeRzXNxY7tgIBqPBViML4zKg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "F3A1877B-B990-4F13-8E87-C90DF070B2C9",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Super Administrator",
                            NormalizedName = "SUPER ADMINISTRATOR"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "Recruiter",
                            NormalizedName = "RECRUITER"
                        },
                        new
                        {
                            Id = 3L,
                            Name = "Candidate",
                            NormalizedName = "CANDIDATE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_claims_role_id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext")
                        .HasColumnName("provider_display_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            RoleId = 1L
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CandidateEducation", b =>
                {
                    b.HasOne("AiRecruitmentPlatform.Domain.Entities.CandidateProfileInformation", "ProfileInformation")
                        .WithMany("Educations")
                        .HasForeignKey("CandidateProfileInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_educations_candidate_profile_informations_candidat");

                    b.Navigation("ProfileInformation");
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CandidateExperience", b =>
                {
                    b.HasOne("AiRecruitmentPlatform.Domain.Entities.CandidateProfileInformation", "ProfileInformation")
                        .WithMany("Experiences")
                        .HasForeignKey("CandidateProfileInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_experiences_candidate_profile_informations_candida");

                    b.Navigation("ProfileInformation");
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CandidateLanguage", b =>
                {
                    b.HasOne("AiRecruitmentPlatform.Domain.Entities.CandidateProfileInformation", "ProfileInformation")
                        .WithMany("Languages")
                        .HasForeignKey("CandidateProfileInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_languages_candidate_profile_informations_candidate");

                    b.Navigation("ProfileInformation");
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CandidateSkill", b =>
                {
                    b.HasOne("AiRecruitmentPlatform.Domain.Entities.CandidateProfileInformation", "ProfileInformation")
                        .WithMany("Skills")
                        .HasForeignKey("CandidateProfileInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_skills_candidate_profile_informations_candidate_pr");

                    b.Navigation("ProfileInformation");
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CandidateSocialLink", b =>
                {
                    b.HasOne("AiRecruitmentPlatform.Domain.Entities.CandidateProfileInformation", "ProfileInformation")
                        .WithOne("SocialLinks")
                        .HasForeignKey("AiRecruitmentPlatform.Domain.Entities.CandidateSocialLink", "CandidateProfileInformationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_candidate_social_links_candidate_profile_informations_candid");

                    b.Navigation("ProfileInformation");
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.JobPosting", b =>
                {
                    b.HasOne("AiRecruitmentPlatform.Domain.Entities.CompanyProfile", "CompanyProfile")
                        .WithMany()
                        .HasForeignKey("CompanyProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_postings_company_profiles_company_profile_id");

                    b.Navigation("CompanyProfile");
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.JobScreeningQuestion", b =>
                {
                    b.HasOne("AiRecruitmentPlatform.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("ScreeningQuestions")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_screening_questions_job_postings_job_posting_id");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.JobSkill", b =>
                {
                    b.HasOne("AiRecruitmentPlatform.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("Skills")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_skills_job_postings_job_posting_id");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_claims_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("AiRecruitmentPlatform.Infrastructure.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("AiRecruitmentPlatform.Infrastructure.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("AiRecruitmentPlatform.Infrastructure.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("AiRecruitmentPlatform.Infrastructure.Identity.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.CandidateProfileInformation", b =>
                {
                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Languages");

                    b.Navigation("Skills");

                    b.Navigation("SocialLinks");
                });

            modelBuilder.Entity("AiRecruitmentPlatform.Domain.Entities.JobPosting", b =>
                {
                    b.Navigation("ScreeningQuestions");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
